version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./html/:/var/www/html/
    container_name: php
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "6666:80"
    volumes:
      - ./html/:/var/www/html/
    container_name: apache
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=password
    container_name: mysql
networks:
  frontend:
  backend:



